.set-or-replace AssetInventory <|
iiotdata
| where isnotempty(Asset)
| distinct Asset
| extend Capacity=real(1200)

//Two records should return from query below
AssetInventory

.set-or-replace ShiftSchedule <|
range times from datetime(2022-05-01) to datetime(2023-05-01) step 8h
| serialize start=times, end=next(times)
| extend dummy=1
| join kind=inner (AssetInventory | extend dummy=1) on dummy
| project Asset,ShiftStart=start,ShiftEnd=end